#!/usr/bin/env ruby

require 'yaml'

app_name=ARGV[0]

types = YAML.load(`docker run app/#{app} cat /app/Procfile`).keys()

ps_file = "#{ENV['DOKKU_ROOT']}/#{app}/PS"
unless File.exists? ps_file
  File.open(ps_file,"w"){|f| f.write "web: 1" }
end
ps = YAML.load_file(ps_file)

# add Procfile process types
types.each do |type|
  unless ps.keys.include? type
    ps[type] = 0
  end
end

# remove the rest if exists
ps.keys.each do |type|
  unless types.include? type
    ps.delete(type)
  end
end

File.open(ps_file, "w"){ |f| f.write ps.to_yaml }