#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

sudo apt-get install -y build-essential libssl-dev libpopt-dev git libpcre3-dev

[[ ! -d "$HOME/haproxy" ]] && git clone http://master.formilux.org/git/people/willy/haproxy.git "$HOME/haproxy"
cd "$HOME/haproxy"
make TARGET=linux2628 CPU=native USE_PCRE=1 USE_OPENSSL=1 USE_ZLIB=1 USE_STATIC_PCRE=1
sudo make install
[[ ! -f "/usr/sbin/haproxy" ]] && sudo ln -s /usr/local/sbin/haproxy /usr/sbin/haproxy
[[ ! -d "/usr/share/haproxy" ]] && sudo mkdir /usr/share/haproxy
[[ ! -f "/etc/init.d/haproxy" ]] && sudo cp $PLUGIN_PATH/valley-haproxy/init.d.haproxy.txt /etc/init.d/haproxy
sudo chmod +x /etc/init.d/haproxy
sudo update-rc.d haproxy defaults
sudo echo "ENABLED=1" > /etc/default/haproxy
sudo adduser --system haproxy
[[ ! -d "/etc/haproxy" ]] && sudo mkdir /etc/haproxy
[[ ! -d "/etc/haproxy/errors" ]] && sudo mkdir /etc/haproxy/errors
sudo cp $HOME/haproxy/examples/errorfiles/* /etc/haproxy/errors
sudo cp $PLUGIN_PATH/valley-haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg
sudo chmod 777 /etc/haproxy/haproxy.cfg

if ! grep -q dokku-haproxy-reload "/etc/sudoers"; then
  touch /etc/sudoers.tmp
  cp /etc/sudoers /tmp/sudoers.new
  echo "%dokku ALL=(ALL)NOPASSWD:/usr/sbin/service haproxy reload # dokku-haproxy-reload" >> /tmp/sudoers.new
  EDITOR="cp /tmp/sudoers.new" visudo
  rm /tmp/sudoers.new
fi

# to update
# cd ~/haproxy
# git pull
# make clean
# make TARGET=linux2628 CPU=native USE_PCRE=1 USE_OPENSSL=1 USE_ZLIB=1
# sudo make install

# sudo service haproxy restart

if [[ ! -f "$DOKKU_ROOT/VHOST" ]]; then
  [[ $(dig +short $(< "$DOKKU_ROOT/HOSTNAME")) ]] && cp "$DOKKU_ROOT/HOSTNAME" "$DOKKU_ROOT/VHOST"
fi