#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

sudo apt-get install -y build-essential libssl-dev libpopt-dev git libpcre3-dev ruby1.9.1-dev rubygems

update-alternatives --set ruby /usr/bin/ruby1.9.1
update-alternatives --set gem /usr/bin/gem1.9.1
gem install bundler

sudo add-apt-repository ppa:vbernat/haproxy-1.5
sudo apt-get update -y
sudo apt-get install haproxy -y

if ! grep -q dokku-haproxy-reload "/etc/sudoers"; then
  touch /etc/sudoers.tmp
  cp /etc/sudoers /tmp/sudoers.new
  echo "%dokku ALL=(ALL)NOPASSWD:/usr/sbin/service haproxy reload # dokku-haproxy-reload" >> /tmp/sudoers.new
  EDITOR="cp /tmp/sudoers.new" visudo
  rm /tmp/sudoers.new
fi

sudo cp $PLUGIN_PATH/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg
sudo chmod 777 /etc/haproxy/haproxy.cfg
sudo echo "ENABLED=1" > /etc/default/haproxy

# sudo service haproxy restart

if [[ ! -f  "$DOKKU_ROOT/VHOST" ]]; then
  [[ $(dig +short $(< "$DOKKU_ROOT/HOSTNAME")) ]] && cp "$DOKKU_ROOT/HOSTNAME" "$DOKKU_ROOT/VHOST"
fi
