#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1"; PORT="$2"
WILDCARD_SSL="$DOKKU_ROOT/ssl"
SSL="$DOKKU_ROOT/$APP/ssl"
ADDR=`hostname`

if [[ -f "$DOKKU_ROOT/VHOST" ]]; then

  VHOST=$(< "$DOKKU_ROOT/VHOST")
  SUBDOMAIN=${APP/%\.${VHOST}/}

  if [[ "$APP" == *.* ]] && [[ "$SUBDOMAIN" == "$APP" ]]; then
    hostname="${APP/\//-}"
  else
    hostname="${APP/\//-}.$VHOST"
  fi

  if [[ ! -f "$DOKKU_ROOT/$APP/PS" ]]; then
    echo "web: 1" > "$DOKKU_ROOT/$APP/PS"
  fi

  echo "http://$hostname" > "$DOKKU_ROOT/$APP/URL"

  pluginhook haproxy-pre-reload $APP $PORT $ADDR $VHOST $SUBDOMAIN $hostname

  sudo service haproxy reload > /dev/null

fi
