#!/usr/bin/env ruby

`set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x`

require 'yaml'

app,repo = ARGV

ps_file = "#{ENV['DOKKU_ROOT']}/#{app}/PS"

ps = YAML.load_file(ps_file)

ps.each do |process_type,count|
  
end

pluginhook reload $APP