#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"; PORT="$2"; REGISTRY=${REGISTRY:=$(valley registry:uri)}

if [ $REGISTRY ]; then

	CONTAINER=$(< "$DOKKU_ROOT/$APP/CONTAINER")
	REPO="$REGISTRY/$APP"
	
	cid=`docker commit $CONTAINER $APP`
	docker tag $cid $REPO
	docker push $REPO
	
	pluginhook host-deploy $APP $REPO

	docker stop $CONTAINER > /dev/null || true

else
	
	echo "!--> REGISTRY URI NOT FOUND"	
	exit 1

fi
