#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

get_registry_uri() {
	uri="$(euca-describe-instances --filter tag-key=type --filter tag-value=registry | grep INSTANCE | awk '{ print $4 }')"
	if [[ ! -z "$uri" ]]; then
		return "$uri:5000"
	fi
}

APP="$1"; PORT="$2"; REGISTRY=${REGISTRY:=$(get_registry_uri)}

if [ $REGISTRY ]; then

	CONTAINER=$(< "$DOKKU_ROOT/$APP/CONTAINER")
	REPO="$REGISTRY/$APP"
	
	cid=`docker commit $CONTAINER $APP`
	docker tag $cid $REPO
	docker push $REPO
	
	pluginhook deploy $APP $REPO

	docker stop $CONTAINER > /dev/null || true

else
	
	echo "!--> REGISTRY URI NOT FOUND"	
	exit 1

fi
